shop_command_index:
    path:     /
    defaults: { _controller: "tontineBundle:Commande:index" }
    methods:  GET

shop_command_show:
    path:     /{id}/show
    defaults: { _controller: "tontineBundle:Commande:show" }
    methods:  GET

shop_command_new:
    path:     /new
    defaults: { _controller: "tontineBundle:Commande:new" }
    methods:  [GET, POST]

shop_command_edit:
    path:     /{id}/edit
    defaults: { _controller: "tontineBundle:Commande:edit" }
    methods:  [GET, POST]

shop_command_delete:
    path:     /{id}/delete
    defaults: { _controller: "tontineBundle:Commande:delete" }
    methods:  DELETE

shop_command_facture_edit:
    path:     /{id}/commande/facture
    defaults: { _controller: "tontineBundle:Commande:printBill" }
    methods:  GET

# fiche de travail

shop_fiche_travail_new:
    path:     /{id}/new
    defaults: { _controller: "tontineBundle:Commande:setFiche" }
    methods:  [GET, POST]

shop_fiche_travail_index:
    path:     /{id}/fiche-de-travail
    defaults: { _controller: "tontineBundle:Commande:indexFiche" }
    methods:  GET
