shop_command_index:
    path:     /
    defaults: { _controller: "tontineBundle:Commande:index" }
    methods:  GET

shop_command_show:
    path:     /{id}/show
    defaults: { _controller: "tontineBundle:Commande:show" }
    methods:  GET

shop_command_new:
    path:     /new
    defaults: { _controller: "tontineBundle:Commande:new" }
    methods:  [GET, POST]

shop_command_edit:
    path:     /{id}/edit
    defaults: { _controller: "tontineBundle:Commande:edit" }
    methods:  [GET, POST]

shop_command_delete:
    path:     /{id}/delete
    defaults: { _controller: "tontineBundle:Commande:delete" }
    methods:  DELETE

shop_command_facture_edit:
    path:     /{id}/commande/facture
    defaults: { _controller: "tontineBundle:Commande:printBill" }
    methods:  GET

# livraison

shop_command_livraison:
    path:     /{id}/livraison-commande
    defaults: { _controller: "tontineBundle:Commande:livraison" }

shop_command_avance_payement:
    path:     /{id}/commande/payement/avance/{action}
    defaults: { _controller: "tontineBundle:Commande:payerAvance", action = null }
    methods:  [GET, POST]

# fiche de travail

shop_fiche_travail_new:
    path:     /{id}/new-fiche
    defaults: { _controller: "tontineBundle:Commande:setFiche" }
    methods:  [GET, POST]

shop_fiche_travail_index:
    path:     /{id}/fiche-de-travail
    defaults: { _controller: "tontineBundle:Commande:indexFiche" }
    methods:  GET

shop_fiche_travail_voir_mesure:
    path:     /{id}/fiche/voir/mesure
    defaults: { _controller: "tontineBundle:Commande:voirMesureFiche" }
    methods:  [GET, POST]

shop_fiche_travail_modif_mesure_form:
    path:     /{id}/fiche/form/modif/mesure
    defaults: { _controller: "tontineBundle:Commande:formModifMesureFiche" }
    methods: [GET, POST]

# etat des benefices

shop_command_etat:
    path:     /etat
    defaults: { _controller: "tontineBundle:Commande:etat" }
    methods:  [POST, GET]