<?php

namespace tontineBundle\Repository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends BaseRepository
{
}
