<?php

namespace tontineBundle\Repository;

use EldoMagan\Doctrine\ORM\BaseRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends BaseRepository
{
    public function findForToDay($user){
        $query = $this->createQueryBuilder('c')->
                where('c.createdBy = :u')->andWhere('c.createdAt LIKE :d')
        ->setParameters(array('d' =>(new \DateTime())->format("Y-m-d").'%', 'u' => $user))
        ->getQuery();

        return $query->getResult();
    }

        public function getByCriteria($critereEtat){
        
       $clients = $this->createQueryBuilder('d');
           $controle=1;   
           if( $critereEtat->getVille()){
              
                     $clients->where("d.ville = :ville ")
                    ->setParameter('ville' , $critereEtat->getVille());
                   $controle=0;  
              
               }
           
           
                 if( $critereEtat->getQuartier()){
                       if ($controle){
                                 $clients->where("d.quartier = :quartier")
                                    ->setParameter('quartier', $critereEtat->getQuartier());
                                 $controle=0;  
                       }
                        else{
                             $clients->andWhere("d.quartier = :quartier")
                                    ->setParameter('quartier', $critereEtat->getQuartier());
                                 $controle=0; 
                            
                        }
               
                       }
                 
                 
                 if( $critereEtat->getTypeMise()){
                      if ($controle){
                                 $clients->leftJoin('d.tontines', 'tontine')->andWhere('tontine.mode = :mode')
                                        ->setParameter('mode',$critereEtat->getTypeMise());
                                  $controle=0;  
                       }else{
                           $clients->leftJoin('d.tontines', 'tontine')->where('tontine.mode = :mode')
                                        ->setParameter('mode', $critereEtat->getTypeMise());
                                  $controle=0; 
                       }
                 }
                 
                return $clients->getQuery()->getResult(); 
        
    }
}
