<?php

namespace tontineBundle\Repository;

/**
 * CommandeModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
