<?php

namespace tontineBundle\Repository;

/**
 * CommandeNomodeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeNomodeleRepository extends \Doctrine\ORM\EntityRepository
{
}
