<?php

namespace tontineBundle\Repository;

/**
 * CommandePagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandePagneRepository extends \Doctrine\ORM\EntityRepository
{
}
