<?php

namespace tontineBundle\Repository;

/**
 * ConditionGeneraleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionGeneraleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotUpdate($version_cg){
        $qb = $this->createQueryBuilder('c');
        
        $qb->where('c.version != :v')->orWhere('c.version IS NULL')->setParameter('v', $version_cg);
        
        return $qb->getQuery()->getResult();
    }
}
