<?php

namespace tontineBundle\Repository;

/**
 * CriteresEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteresEtatRepository extends \Doctrine\ORM\EntityRepository
{
}
