<?php

namespace tontineBundle\Repository;

/**
 * FinContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinContratRepository extends \Doctrine\ORM\EntityRepository
{
}
