<?php

namespace tontineBundle\Repository;

use EldoMagan\Doctrine\ORM\BaseRepository;

/**
 * NomodeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomodeleRepository extends BaseRepository
{
  
}
