<?php

namespace tontineBundle\Repository;

/**
 * PagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagneRepository extends \Doctrine\ORM\EntityRepository
{
}
