<?php

namespace tontineBundle\Repository;

/**
 * ProvisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvisionRepository extends \Doctrine\ORM\EntityRepository
{
}
