<?php

namespace tontineBundle\Repository;

/**
 * ResiliationContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResiliationContratRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByCriteria($critereEtat){
     $controle=1;
     $contrats = $this->createQueryBuilder('d');
           
        if( $critereEtat->getPeriode()->getdateDebut()&&$critereEtat->getPeriode()->getdateFin()){
              
                     $contrats->where("d.dateResiliation >= :dated and d.dateResiliation <= :datef")
                    ->setParameters(array('dated'=> $critereEtat->getPeriode()->getdateDebut(),'datef'=>$critereEtat->getPeriode()->getdateFin()));
                   $controle=0;  
              
               }
         
           
                 if( $critereEtat->getTypeMotif()){
                       if ($controle){
                                 $contrats->where("d.typeMotif = :typeMotif")
                                    ->setParameter('typeMotif', $critereEtat->getTypeMotif());
                                 $controle=0;  
                       }
                        else{
                             $contrats->andWhere("d.typeMotif = :typeMotif")
                                    ->setParameter('typeMotif', $critereEtat->getTypeMotif());
                                 $controle=0; 
                            
                        }
               
                       }
                 
               
                return $contrats->getQuery()->getResult();
}

                        }
