<?php

namespace tontineBundle\Repository;

/**
 * TontineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TontineRepository extends BaseRepository
{
}
