<?php

namespace tontineBundle\Repository;

/**
 * TransfertFondsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransfertFondsRepository extends BaseRepository
{
    public function getByCriteria($critereEtat){
        $before = false;
        $qb = $this->createQueryBuilder('d');
        if($critereEtat->getPeriode()){
            $qb->where("d.createdAt <= :df AND d.createdAt >= :dd")
                    ->setParameters(array('dd' => $critereEtat->getPeriode()->getDateDebut(), 
                        'df' => $critereEtat->getPeriode()->getDateFin()));
            $before = true;
        }
        /*if($critereEtat->getClient()){
            if($before)
                $qb->andWhere("d.client = :cl")
                    ->setParameter('cl', $critereEtat->getClient());        
            else
                $qb->where("d.client = :cl")
                    ->setParameter('cl', $critereEtat->getClient());
            $before = true;
        }
        if($critereEtat->getQuartier()){
            if($before)
                $qb->leftJoin('d.client', 'c')->andWhere('c.quartier = :q')
                    ->setParameter('q', "%".$critereEtat->getQuartier()."%");     
            else
                $qb->leftJoin('d.client', 'c')->where('c.quartier = :q')
                    ->setParameter('q', "%".$critereEtat->getQuartier()."%");
             $before = true;
        }else{
            if($critereEtat->getVille()){
                if($before)
                    $qb->leftJoin('d.client', 'c')->andWhere('c.ville = :v')
                        ->setParameter('v', "%".$critereEtat->getVille()."%");     
                else
                    $qb->leftJoin('d.client', 'c')->where('c.ville = :v')
                        ->setParameter('v', "%".$critereEtat->getVille()."%");
                 $before = true;
            }
        }*/
	return $qb->getQuery()->getResult();
    }
}
