<?php

namespace tontineBundle\Repository;

/**
 * TypeTontineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTontineRepository extends \Doctrine\ORM\EntityRepository
{
}
