imports:
    - { resource: parameters.yml }    
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: security_roles.yml }
    - { resource: "@tontineBundle/Resources/config/services.yml" }
    - { resource: "@tontineApiBundle/Resources/config/services.yml" }
    - { resource: "@GSPBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    #php_errors:
     #   log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        menuCounters: '@tontine.menu_counters'
        api_server_name: "%api_server_name%"

# Doctrine Configuration
doctrine:
    dbal:
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        default_connection: tontine
        connections:
            tontine:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                # if using pdo_sqlite as your database driver:
                #   1. add the path in parameters.yml
                #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
                #   2. Uncomment database_path in parameters.yml.dist
                #   3. Uncomment next line:
                #path:     "%database_path%"
            gspmanager:
                driver:   pdo_mysql
                host:     "%gspmanager_database_host%"
                port:     "%gspmanager_database_port%"
                dbname:   "%gspmanager_database_name%"
                user:     "%gspmanager_database_user%"
                password: "%gspmanager_database_password%"
                charset: UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        # auto_mapping: true
        default_entity_manager: tontine
        entity_managers:
            tontine:
                default_repository_class: EldoMagan\Doctrine\ORM\BaseRepository
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: tontine
                mappings:
                    AppBundle:  ~
                    tontineBundle: ~
            gspmanager:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: gspmanager
                mappings:
                    GSPBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
# FosUser
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: tontineBundle\Entity\Agent
    group:
        group_class: AppBundle\Entity\Group
    registration:
        form:
            type: tontineBundle\Form\AgentType

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# Jms
jms_serializer:
    handlers:
        datetime:
            default_format: "d-m-Y\\TH:i:sP"
            default_timezone: "UTC"
    metadata:
        auto_detection: true
        directories:
            tontine:
                namespace_prefix: "tontineBundle"
                path: "@tontineBundle/Resources/config/serializer"
# FosRest
fos_rest:    
    disable_csrf_role: true
    serializer:
        serialize_null:  true
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/(api|oauth)', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
    view:
        view_response_listener: 'force'
        ##--------
        formats:
            xml: true
            json : true
            ##---- 

    routing_loader:
        include_format: false    
    exception:
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true

fos_js_routing:
    routes_to_expose: '^[^_]'
    
guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        api_gspmanager:
            base_url: %api_gspmanager_endpoint%

            # custom headers (@deprecated, will be removed in v6; new: "headers" in options (see below))
            headers:
                Accept: "application/json"

            # guzzle client options (full description here: https://guzzle.readthedocs.org/en/latest/request-options.html)
            # NOTE: "headers" option is not accepted here as it is provided as described above.
            options:
                auth:
                    - fa # login
                    - fa # password
                timeout: 300000000

            # plugin settings
            plugin:
                wsse:
                    username:   "fa"
                    password:   "fa"

core23_dompdf:
    defaults:
        dpi: 150
        defaultPaperSize: A4
        defaultPaperOrientation: "landscape" # portrait or landscape