parameters:
    default_roles:
        - ROLE_CLIENT_VIEW
        - ROLE_AGENT_VIEW
        - ROLE_CLIENT_CREATE
        - ROLE_PAGNE_VIEW
        
    roles_sections:
        - 
            label: Opérations sur les clients
            roles:
                ROLE_CLIENT_VIEW: Voir la liste des clients
                ROLE_CLIENT_CREATE: Enregistrer un nouveau client
                ROLE_CLIENT_EDIT: Modifier les informations d'un client
                ROLE_CLIENT_DELETE: Supprimer un client
                

        - 
            label: Opérations sur les agents
            roles:    
                ROLE_AGENT_VIEW: Voir la liste des agents
                ROLE_AGENT_CREATE: Enregistrer un nouvel agent
                ROLE_AGENT_EDIT: Modifier les informations d'un agent
                ROLE_AGENT_ENABLE: Activer un agent
                ROLE_AGENT_DISABLE: Désactiver un agent

        - 
            label: Opérations sur les agences de Global Design
            roles:    
                ROLE_AGENCY_VIEW: Voir la liste des agences
                ROLE_AGENCY_CREATE: Ajouter une nouvelle agence
                ROLE_AGENCY_EDIT: Modifier les informations d'une agence
                ROLE_AGENCY_DELETE: Supprimer une agence

        - 
            label: Opérations sur les commandes des clients
            roles:    
                ROLE_COMMANDE_VIEW: Voir la liste des commandes
                ROLE_COMMANDE_CREATE: Enregistrer une nouvelle commande
                ROLE_COMMANDE_EDIT: Modifier les informations d'une commande
                ROLE_BENEFICE_VIEW: Voir les bénéfices
                ROLE_COMMANDE_DELETE: Supprimer une commande


        -
            label: Paramètres de l'application
            roles:
                ROLE_SETTING_EDIT: Modifier les paramètres
                ROLE_GROUP_VIEW: Voir la liste des profils d'agent
                ROLE_GROUP_CREATE: Créer un profil d'agent
                ROLE_GROUP_EDIT: Modifier les droits d'un profil
                ROLE_GROUP_DELETE: Modifier un profil d'agent