# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        tontineBundle\Entity\Agent: sha512
        
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
        #    memory: ~
        main:
            id: fos_user.user_provider.username_email
        auth_token_user_provider:
            id: user_auth_token_provider            

    role_hierarchy:
        
        ROLE_GSP_TONTINE_CAISSIERE:             [ROLE_USER, ROLE_CAISSIERE]
        ROLE_GSP_TONTINE_AGENT_DE_TRANSFERT:    [ROLE_USER, ROLE_AGENT_TRANSFERT]
        ROLE_GSP_TONTINE_COLLECTEUR:            [ROLE_USER, ROLE_COLLECTEUR]
        ROLE_GSP_TONTINE_ADMIN:                 [ROLE_USER, ROLE_ADMIN, ROLE_GSP_TONTINE_COLLECTEUR, ROLE_GSP_TONTINE_CAISSIERE]
        ROLE_GSP_TONTINE_SUPER_ADMIN:           [ROLE_USER, ROLE_GSP_TONTINE_ADMIN, ROLE_CAISSIERE, ROLE_AGENT_TRANSFERT, ROLE_COLLECTEUR, ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_authentication:
            pattern: ^/api/authenticate
            security: false

        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~                  

        main:
            #anonymous: ~
            # activate different ways to authenticate
            pattern:    ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /
                
            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:        
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_GSP_TONTINE_SUPER_ADMIN, ROLE_GSP_TONTINE_ADMIN] }
        # - { path: ^/agents, role: [ROLE_GSP_TONTINE_SUPER_ADMIN, ROLE_GSP_TONTINE_ADMIN] }
        # - { path: ^/etat, role: [ROLE_GSP_TONTINE_SUPER_ADMIN, ROLE_GSP_TONTINE_ADMIN] }
        - { path: ^/myprofile, role: [ROLE_USER] }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
