services:
#    tontine_api.example:
#        class: tontineApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    user_auth_token_provider:
        class: tontineApiBundle\Security\UserAuthTokenProvider
        arguments: ["@doctrine.orm.entity_manager"]
        public:    false

    auth_token_authenticator:
        class:     tontineApiBundle\Security\UserAuthTokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false
