<?php

namespace Proxies\__CG__\tontineBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fournisseur extends \tontineBundle\Entity\Fournisseur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'id', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'nom', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'prenom', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'photo', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'contacts', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'contactsConfirmation', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'adresse', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'createdAt', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'updatedAt', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'createdBy', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'updatedBy', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'filePhoto'];
        }

        return ['__isInitialized__', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'id', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'nom', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'prenom', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'photo', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'contacts', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'contactsConfirmation', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'adresse', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'createdAt', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'updatedAt', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'createdBy', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'updatedBy', '' . "\0" . 'tontineBundle\\Entity\\Fournisseur' . "\0" . 'filePhoto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fournisseur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getContactsConfirmation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactsConfirmation', []);

        return parent::getContactsConfirmation();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactsConfirmation($contactsConfirmation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactsConfirmation', [$contactsConfirmation]);

        return parent::setContactsConfirmation($contactsConfirmation);
    }

    /**
     * {@inheritDoc}
     */
    public function isContactValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isContactValid', []);

        return parent::isContactValid();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(\tontineBundle\Entity\Agent $createdBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy(\tontineBundle\Entity\Agent $updatedBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacts($contacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacts', [$contacts]);

        return parent::setContacts($contacts);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function name()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'name', []);

        return parent::name();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getFilePhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilePhoto', []);

        return parent::getFilePhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilePhoto(\Symfony\Component\HttpFoundation\File\File $filePhoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilePhoto', [$filePhoto]);

        return parent::setFilePhoto($filePhoto);
    }

}
