tontineBundle\Entity\Client:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        nom:
            expose: true
        prenom:
            expose: true
        contacts:
            expose: true
        adresse:
            expose: true
